
all:

run_server:
	echo Server on port 8836
	/Users/corwin/bin/go-server --dir=. --port=8836 & 

deploy:
	scp index.html pschlump@192.154.97.74:/home/pschlump/go-svr/dApp-coupons
	scp js/index.js pschlump@192.154.97.74:/home/pschlump/go-svr/dApp-coupons/js

